/**
 * List of irreguler verbs
 */
let verbList = [
  //   {
  //     verb1Name: "awake",
  //     verb1Pronunciation: "eweyk",
  //     verb2Name: "awoke",
  //     verb2Pronunciation: "evog",
  //     verb3Name: "awoken",
  //     verb3Pronunciation: "evokın",
  //     verbTurkish: "uyanmak",
  //     verb1Exp: "I usually wake",
  //     verb2Exp: "",
  //     verb3Exp: "",
  //   },
  {
    verb1Name: "be",
    verb1Pronunciation: "bi",
    verb2Name: "was/were",
    verb2Pronunciation: "vaz/vör",
    verb3Name: "been",
    verb3Pronunciation: "biin",
    verbTurkish: "olmak",
    verb1Exp: "She'll be at the party next weekend.",
    verb2Exp: "Tom was in New York yesterday.",
    verb3Exp: "I've been at this job for a long time.",
  },
  {
    verb1Name: "tell",
    verb1Pronunciation: "tel",
    verb2Name: "told",
    verb2Pronunciation: "told",
    verb3Name: "told",
    verb3Pronunciation: "told",
    verbTurkish: "söylemek anlatmak",
    verb1Exp: "Can you tell me your name?",
    verb2Exp: "He told her a funny story last night.",
    verb3Exp: "She has told me about her trip.",
  },
  {
    verb1Name: "speak",
    verb1Pronunciation: "sıpik",
    verb2Name: "spoke",
    verb2Pronunciation: "sıpog",
    verb3Name: "spoken",
    verb3Pronunciation: "sıpokın",
    verbTurkish: "konuşmak",
    verb1Exp: "I speak Svedish fuently.",
    verb2Exp: "She spoke to the manager about the issue.",
    verb3Exp: "He has spoken to his boss about the project.",
  },
  {
    verb1Name: "see",
    verb1Pronunciation: "sii",
    verb2Name: "saw",
    verb2Pronunciation: "sov",
    verb3Name: "seen",
    verb3Pronunciation: "siın",
    verbTurkish: "görmek",
    verb1Exp: "She's going to see her friend next weekend.",
    verb2Exp: "I saw the film last week.",
    verb3Exp: "Have you seen Angie yet?",
  },
  {
    verb1Name: "run",
    verb1Pronunciation: "ran",
    verb2Name: "ran",
    verb2Pronunciation: "ren",
    verb3Name: "run",
    verb3Pronunciation: "ran",
    verbTurkish: "koşmak",
    verb1Exp: "David usually runs two miles a day.",
    verb2Exp: "I ran four miles yesterday.",
    verb3Exp: "We've run out of milk, so I'll go to the store.",
  },
  {
    verb1Name: "write",
    verb1Pronunciation: "rayt",
    verb2Name: "wrote",
    verb2Pronunciation: "root",
    verb3Name: "written",
    verb3Pronunciation: "ritın",
    verbTurkish: "yazmak",
    verb1Exp: "I write in my journal every night.",
    verb2Exp: "She wrote a love letter to her boyfriend.",
    verb3Exp: "He has written a report for work",
  },
  {
    verb1Name: "catch",
    verb1Pronunciation: "ketç",
    verb2Name: "caught",
    verb2Pronunciation: "kouht",
    verb3Name: "caught",
    verb3Pronunciation: "kouht",
    verbTurkish: "tutmak - yakalamak",
    verb1Exp: "Can you catch the ball, please?",
    verb2Exp: "He caught the train just in time.",
    verb3Exp: "She has caught a cold.",
  },
  {
    verb1Name: "choose",
    verb1Pronunciation: "çıuz",
    verb2Name: "chose",
    verb2Pronunciation: "çoz",
    verb3Name: "chosen",
    verb3Pronunciation: "çuızın",
    verbTurkish: "seçmek",
    verb1Exp: "I choose to eat healthy food.",
    verb2Exp: "She chose the red dress for the party.",
    verb3Exp: "He has already chosen his favorite book.",
  },
  {
    verb1Name: "come",
    verb1Pronunciation: "kam",
    verb2Name: "came",
    verb2Pronunciation: "keym",
    verb3Name: "come",
    verb3Pronunciation: "kam",
    verbTurkish: "gelmek",
    verb1Exp: "We'll leave as soon as you get home.",
    verb2Exp: "We left the book at home.",
    verb3Exp: "He's left the house early this morning.",
  },
  {
    verb1Name: "leave",
    verb1Pronunciation: "liıv",
    verb2Name: "left",
    verb2Pronunciation: "left",
    verb3Name: "",
    verb3Pronuncleftiation: "left",
    verbTurkish: "ayrılmak",
    verb1Exp: "I leave for work at 8 am.",
    verb2Exp: "She left the party early last night.",
    verb3Exp: "He has already left for the airport.",
  },
  {
    verb1Name: "keep",
    verb1Pronunciation: "kiip",
    verb2Name: "kept",
    verb2Pronunciation: "kept",
    verb3Name: "kept",
    verb3Pronunciation: "kept",
    verbTurkish: "saklamak",
    verb1Exp: "I'll keep your secret.",
    verb2Exp: "John kept the door open for his mother.",
    verb3Exp: "Have you kept your word to Peter?",
  },
  {
    verb1Name: "hold",
    verb1Pronunciation: "hoold",
    verb2Name: "held",
    verb2Pronunciation: "held",
    verb3Name: "held",
    verb3Pronunciation: "heeld",
    verbTurkish: "tutmak",
    verb1Exp: "Hold on for a few more minutes. ",
    verb2Exp: "She held on tightly and entered the tunnel.",
    verb3Exp: "I've held her hand before.",
  },
  {
    verb1Name: "hear",
    verb1Pronunciation: "hiyır",
    verb2Name: "heard",
    verb2Pronunciation: "hörd",
    verb3Name: "heard",
    verb3Pronunciation: "hörd",
    verbTurkish: "duymak",
    verb1Exp: "I hear someone knocking at the door",
    verb2Exp: "Yesterday, she heard a strange noise.",
    verb3Exp: "He has heard the news already",
  },
  {
    verb1Name: "give",
    verb1Pronunciation: "giv",
    verb2Name: "gave",
    verb2Pronunciation: "geyv",
    verb3Name: "given",
    verb3Pronunciation: "givın",
    verbTurkish: "vermek",
    verb1Exp: "I'll give you a call next week. ",
    verb2Exp: "They gave us an early appointment.",
    verb3Exp: "He's given up on trying to learn Japanese.",
  },
  {
    verb1Name: "bring",
    verb1Pronunciation: "bıring",
    verb2Name: "brought",
    verb2Pronunciation: "bıroukt",
    verb3Name: "brought",
    verb3Pronunciation: "bıroukt",
    verbTurkish: "getirmek",
    verb1Exp: "Can you bring me some water.",
    verb2Exp: "He brought his girlfriend to the party.",
    verb3Exp: "She has brought her own lunch.",
  },
  {
    verb1Name: "forget",
    verb1Pronunciation: "forget",
    verb2Name: "forgot",
    verb2Pronunciation: "forgat",
    verb3Name: "forgotten",
    verb3Pronunciation: "forgatın",
    verbTurkish: "unutmak",
    verb1Exp: "I forget the words I just learned",
    verb2Exp: "I forgot my pen at home. Can I borrow yours?",
    verb3Exp: "Have you forgotten that you had an appointment?",
  },
  {
    verb1Name: "go",
    verb1Pronunciation: "go",
    verb2Name: "went",
    verb2Pronunciation: "vent",
    verb3Name: "gone",
    verb3Pronunciation: "gan",
    verbTurkish: "gitmek",
    verb1Exp: "She's going to ride the bus to work today.",
    verb2Exp: "I went to the party last week. ",
    verb3Exp: "Have you ever gone on vacation alone?",
  },
  {
    verb1Name: "drive",
    verb1Pronunciation: "dırayv",
    verb2Name: "drove",
    verb2Pronunciation: "dırov",
    verb3Name: "driven",
    verb3Pronunciation: "dırayvın",
    verbTurkish: "araba sürmek",
    verb1Exp: "He's going to drive to the airport this evening. ",
    verb2Exp: "I drove to the basketball game after work.",
    verb3Exp: "Have you ever driven across the U.S.?",
  },
  {
    verb1Name: "feel",
    verb1Pronunciation: "fiıl",
    verb2Name: "felt",
    verb2Pronunciation: "felt",
    verb3Name: "felt",
    verb3Pronunciation: "felt",
    verbTurkish: "hissetmek",
    verb1Exp: "I feel happy today.",
    verb2Exp: "She felt sick yesterday morning.",
    verb3Exp: "He has felt tired all day.",
  },
  {
    verb1Name: "think",
    verb1Pronunciation: "tink",
    verb2Name: "thought",
    verb2Pronunciation: "dout",
    verb3Name: "thought",
    verb3Pronunciation: "dout",
    verbTurkish: "düşünmek",
    verb1Exp: "I think you are right.",
    verb2Exp: "She thought it was funny.",
    verb3Exp: "He has thought about it",
  },
  {
    verb1Name: "become",
    verb1Pronunciation: "bikam",
    verb2Name: "became",
    verb2Pronunciation: "bikeym",
    verb3Name: "become",
    verb3Pronunciation: "bikam",
    verbTurkish: "olmak - haline gelmek",
    verb1Exp: "I'll become your friend if you move here.",
    verb2Exp: "The situation became a problem for Bob.",
    verb3Exp: "Jason has become an excellent doctor.",
  },
  {
    verb1Name: "begin",
    verb1Pronunciation: "bigin",
    verb2Name: "began",
    verb2Pronunciation: "bigen",
    verb3Name: "begun",
    verb3Pronunciation: "bigan",
    verbTurkish: "başlamak",
    verb1Exp: "She'll begin to explain in a moment.",
    verb2Exp: "I began to work early this morning.",
    verb3Exp: "They haven't begun the play yet.",
  },
  {
    verb1Name: "take",
    verb1Pronunciation: "teyk",
    verb2Name: "took",
    verb2Pronunciation: "tuuk",
    verb3Name: "taken",
    verb3Pronunciation: "teykın",
    verbTurkish: "almak",
    verb1Exp: "He take a pencil",
    verb2Exp: "She took her medication.",
    verb3Exp: "He has taken his medicine already.",
  },
  {
    verb1Name: "buy",
    verb1Pronunciation: "bay",
    verb2Name: "bought",
    verb2Pronunciation: "bouht",
    verb3Name: "bought",
    verb3Pronunciation: "bouht",
    verbTurkish: "satın almak",
    verb1Exp: "I usually buy my vegetables at a country stand.",
    verb2Exp: "Janice bought a new watch last week.",
    verb3Exp: "He's bought more than 10 cars in his life.",
  },
  //   {
  //       verb1Name: 'beat',
  //       verb1Pronunciation: 'biıt',
  //       verb2Name: 'beat',
  //       verb2Pronunciation: 'biıt',
  //       verb3Name: 'beaten',
  //       verb3Pronunciation: 'bitın',
  //       verbTurkish: 'dovmek',
  //    verb1Exp: "",
  //     verb2Exp: "",
  //     verb3Exp: "",
  //   },
  //   {
  //       verb1Name: 'bend',
  //       verb1Pronunciation: 'bend',
  //       verb2Name: 'bent',
  //       verb2Pronunciation: 'bent',
  //       verb3Name: 'bent',
  //       verb3Pronunciation: 'bent',
  //       verbTurkish: 'bükmek',
  //    verb1Exp: "",
  //     verb2Exp: "",
  //     verb3Exp: "",
  //   },
  //   {
  //       verb1Name: 'bet',
  //       verb1Pronunciation: 'bet',
  //       verb2Name: 'bet',
  //       verb2Pronunciation: 'bet',
  //       verb3Name: 'bet',
  //       verb3Pronunciation: 'bet',
  //       verbTurkish: 'bahse girmek',
  //    verb1Exp: "",
  //     verb2Exp: "",
  //     verb3Exp: "",
  //   },
  //   {
  //       verb1Name: 'bid',
  //       verb1Pronunciation: 'biid',
  //       verb2Name: 'bid',
  //       verb2Pronunciation: 'biid',
  //       verb3Name: 'bid',
  //       verb3Pronunciation: 'biid',
  //       verbTurkish: 'emretmek',
  //    verb1Exp: "",
  //     verb2Exp: "",
  //     verb3Exp: "",
  //   },
  //   {
  //       verb1Name: 'bite',
  //       verb1Pronunciation: 'bayt',
  //       verb2Name: 'bit',
  //       verb2Pronunciation: 'bit',
  //       verb3Name: 'bitten',
  //       verb3Pronunciation: 'bitın',
  //       verbTurkish: 'ısırmak',
  //    verb1Exp: "",
  //     verb2Exp: "",
  //     verb3Exp: "",
  //   },
  //   {
  //       verb1Name: 'blow',
  //       verb1Pronunciation: 'bılov',
  //       verb2Name: 'blew',
  //       verb2Pronunciation: 'bıluv',
  //       verb3Name: 'blown',
  //       verb3Pronunciation: 'bılovn',
  //       verbTurkish: 'esmek',
  //    verb1Exp: "",
  //     verb2Exp: "",
  //     verb3Exp: "",
  //   },
  //   {
  //       verb1Name: 'break',
  //       verb1Pronunciation: 'bireyk',
  //       verb2Name: 'broke',
  //       verb2Pronunciation: 'bırog',
  //       verb3Name: 'broken',
  //       verb3Pronunciation: 'bırokın',
  //       verbTurkish: 'kırmak',
  //    verb1Exp: "",
  //     verb2Exp: "",
  //     verb3Exp: "",
  //   },

  //   {
  //       verb1Name: 'build',
  //       verb1Pronunciation: 'build',
  //       verb2Name: 'built',
  //       verb2Pronunciation: 'built',
  //       verb3Name: 'built',
  //       verb3Pronunciation: 'built',
  //       verbTurkish: 'inşa etmek',
  //    verb1Exp: "",
  //     verb2Exp: "",
  //     verb3Exp: "",
  //   },
  //   {
  //       verb1Name: 'burst',
  //       verb1Pronunciation: 'borst',
  //       verb2Name: 'burst',
  //       verb2Pronunciation: 'borst',
  //       verb3Name: 'burst',
  //       verb3Pronunciation: 'borst',
  //       verbTurkish: 'patlamak',
  //    verb1Exp: "",
  //     verb2Exp: "",
  //     verb3Exp: "",
  //   },

  //   {
  //       verb1Name: 'cost',
  //       verb1Pronunciation: 'kost',
  //       verb2Name: 'cost',
  //       verb2Pronunciation: 'kost',
  //       verb3Name: 'cost',
  //       verb3Pronunciation: 'kost',
  //       verbTurkish: 'mâl olmak',
  //    verb1Exp: "",
  //     verb2Exp: "",
  //     verb3Exp: "",
  //   },
  //   {
  //       verb1Name: 'creep',
  //       verb1Pronunciation: 'kırip',
  //       verb2Name: 'crept',
  //       verb2Pronunciation: 'kırept',
  //       verb3Name: 'crept',
  //       verb3Pronunciation: 'kırept',
  //       verbTurkish: 'emeklemek',
  //    verb1Exp: "",
  //     verb2Exp: "",
  //     verb3Exp: "",
  //   },
  {
    verb1Name: "cut",
    verb1Pronunciation: "kat",
    verb2Name: "cut",
    verb2Pronunciation: "kat",
    verb3Name: "cut",
    verb3Pronunciation: "kat",
    verbTurkish: "kesmek",
    verb1Exp: "How many pieces have you cut?",
    verb2Exp: "I cut my finger on a glass yesterday.",
    verb3Exp: "The boy never cuts his own steak.",
  },
  //   {
  //       verb1Name: 'dig',
  //       verb1Pronunciation: 'dig',
  //       verb2Name: 'dug',
  //       verb2Pronunciation: 'dag',
  //       verb3Name: 'dug',
  //       verb3Pronunciation: 'dag',
  //       verbTurkish: 'kazmak',
  //    verb1Exp: "",
  //     verb2Exp: "",
  //     verb3Exp: "",
  //   },
  //   {
  //       verb1Name: 'do',
  //       verb1Pronunciation: 'du',
  //       verb2Name: 'did',
  //       verb2Pronunciation: 'did',
  //       verb3Name: 'done',
  //       verb3Pronunciation: 'dan',
  //       verbTurkish: 'yapmak',
  //    verb1Exp: "",
  //     verb2Exp: "",
  //     verb3Exp: "",
  //   },
  //   {
  //       verb1Name: 'draw',
  //       verb1Pronunciation: 'dırov',
  //       verb2Name: 'drew',
  //       verb2Pronunciation: 'dıruv',
  //       verb3Name: 'drawn',
  //       verb3Pronunciation: 'dırovn',
  //       verbTurkish: 'çizmek',
  //    verb1Exp: "",
  //     verb2Exp: "",
  //     verb3Exp: "",
  //   },

  //   //   {
  //   //       verb1Name: 'drink',
  //   //       verb1Pronunciation: 'dıring',
  //   //       verb2Name: 'drank',
  //   //       verb2Pronunciation: 'direng',
  //   //       verb3Name: 'drunk',
  //   //       verb3Pronunciation: 'dırang',
  //   //       verbTurkish: 'içmek',
  //   //    verb1Exp: "I'll drink something when I get there. ",
  //   //     verb2Exp: "I was so thirsty I drank two bottles of water.",
  //   //     verb3Exp: "Have you drunk any water yet?",
  //   //   },
  {
    verb1Name: "eat",
    verb1Pronunciation: "iit",
    verb2Name: "ate",
    verb2Pronunciation: "eyt",
    verb3Name: "eaten",
    verb3Pronunciation: "itın",
    verbTurkish: "yemek yemek",
    verb1Exp: "Where did you eat dinner yesterday?",
    verb2Exp: "We ate lunch early today.",
    verb3Exp: "Have you eaten already?",
  },
  //   {
  //       verb1Name: 'fall',
  //       verb1Pronunciation: 'fol',
  //       verb2Name: 'fell',
  //       verb2Pronunciation: 'fel',
  //       verb3Name: 'fallen',
  //       verb3Pronunciation: 'follın',
  //       verbTurkish: 'düşmek',
  //    verb1Exp: "",
  //     verb2Exp: "",
  //     verb3Exp: "",
  //   },
  //   {
  //       verb1Name: 'feed',
  //       verb1Pronunciation: 'fiid',
  //       verb2Name: 'fed',
  //       verb2Pronunciation: 'fed',
  //       verb3Name: 'fed',
  //       verb3Pronunciation: 'fed',
  //       verbTurkish: 'beslemek',
  //    verb1Exp: "",
  //     verb2Exp: "",
  //     verb3Exp: "",
  //   },

  //   {
  //       verb1Name: 'fight',
  //       verb1Pronunciation: 'fayt',
  //       verb2Name: 'fought',
  //       verb2Pronunciation: 'fouht',
  //       verb3Name: 'fought',
  //       verb3Pronunciation: 'fouht',
  //       verbTurkish: 'kavga etmek',
  //    verb1Exp: "",
  //     verb2Exp: "",
  //     verb3Exp: "",
  //   },
  {
    verb1Name: "find",
    verb1Pronunciation: "faynd",
    verb2Name: "found",
    verb2Pronunciation: "faund",
    verb3Name: "found",
    verb3Pronunciation: "faund",
    verbTurkish: "bulmak",
    verb1Exp: "I'll find him, don't worry!",
    verb2Exp: "I found this book on that table over there.",
    verb3Exp: "Have you found him yet?",
  },
  //   {
  //       verb1Name: 'fly',
  //       verb1Pronunciation: 'fılay',
  //       verb2Name: 'flew',
  //       verb2Pronunciation: 'fıliuv',
  //       verb3Name: 'flown',
  //       verb3Pronunciation: 'fılavn',
  //       verbTurkish: 'uçmak',
  //    verb1Exp: "",
  //     verb2Exp: "",
  //     verb3Exp: "",
  //   },
  //   {
  //       verb1Name: 'forbid',
  //       verb1Pronunciation: 'forbıid',
  //       verb2Name: 'forbade',
  //       verb2Pronunciation: 'forbeyt',
  //       verb3Name: 'forbidden',
  //       verb3Pronunciation: 'forbidın',
  //       verbTurkish: 'yasaklamak',
  //    verb1Exp: "",
  //     verb2Exp: "",
  //     verb3Exp: "",
  //   },

  //   {
  //       verb1Name: 'forgive',
  //       verb1Pronunciation: 'forgiv',
  //       verb2Name: 'forgave',
  //       verb2Pronunciation: 'forgeyv',
  //       verb3Name: 'forgiven',
  //       verb3Pronunciation: 'forgivın',
  //       verbTurkish: 'affetmek',
  //    verb1Exp: "",
  //     verb2Exp: "",
  //     verb3Exp: "",
  //   },
  //   {
  //       verb1Name: 'freeze',
  //       verb1Pronunciation: 'fıriiz',
  //       verb2Name: 'froze',
  //       verb2Pronunciation: 'fırooz',
  //       verb3Name: 'frozen',
  //       verb3Pronunciation: 'frozın',
  //       verbTurkish: 'dondurmak',
  //    verb1Exp: "",
  //     verb2Exp: "",
  //     verb3Exp: "",
  //   },
  //   {
  //       verb1Name: 'get',
  //       verb1Pronunciation: 'get',
  //       verb2Name: 'got',
  //       verb2Pronunciation: 'gat',
  //       verb3Name: 'gotten',
  //       verb3Pronunciation: 'gatın',
  //       verbTurkish: 'elde etmek',
  //    verb1Exp: "",
  //     verb2Exp: "",
  //     verb3Exp: "",
  //   },

  //   {
  //       verb1Name: 'grow',
  //       verb1Pronunciation: 'gırov',
  //       verb2Name: 'grew',
  //       verb2Pronunciation: 'gırıuv',
  //       verb3Name: 'grown',
  //       verb3Pronunciation: 'gırovn',
  //       verbTurkish: 'büyümek',
  //    verb1Exp: "",
  //     verb2Exp: "",
  //     verb3Exp: "",
  //   },
  //   {
  //       verb1Name: 'hang',
  //       verb1Pronunciation: 'heng',
  //       verb2Name: 'hung',
  //       verb2Pronunciation: 'hang',
  //       verb3Name: 'hung',
  //       verb3Pronunciation: 'hang',
  //       verbTurkish: 'asmak',
  //    verb1Exp: "",
  //     verb2Exp: "",
  //     verb3Exp: "",
  //   },
  //   {
  //       verb1Name: 'have',
  //       verb1Pronunciation: 'hev',
  //       verb2Name: 'had',
  //       verb2Pronunciation: 'hed',
  //       verb3Name: 'had',
  //       verb3Pronunciation: 'hed',
  //       verbTurkish: 'sahip olmak',
  //    verb1Exp: "",
  //     verb2Exp: "",
  //     verb3Exp: "",
  //   },

  //   {
  //       verb1Name: 'hide',
  //       verb1Pronunciation: 'hayd',
  //       verb2Name: 'hid',
  //       verb2Pronunciation: 'hid',
  //       verb3Name: 'hidden',
  //       verb3Pronunciation: 'hidın',
  //       verbTurkish: 'gizlemek',
  //    verb1Exp: "",
  //     verb2Exp: "",
  //     verb3Exp: "",
  //   },
  //   {
  //       verb1Name: 'hit',
  //       verb1Pronunciation: 'hid',
  //       verb2Name: 'hit',
  //       verb2Pronunciation: 'hid',
  //       verb3Name: 'hit',
  //       verb3Pronunciation: 'hid',
  //       verbTurkish: 'vurmak',
  //    verb1Exp: "",
  //     verb2Exp: "",
  //     verb3Exp: "",
  //   },

  //   {
  //       verb1Name: 'hurt',
  //       verb1Pronunciation: 'hört',
  //       verb2Name: 'hurt',
  //       verb2Pronunciation: 'hört',
  //       verb3Name: 'hurt',
  //       verb3Pronunciation: 'hört',
  //       verbTurkish: 'incinmek',
  //    verb1Exp: "",
  //     verb2Exp: "",
  //     verb3Exp: "",
  //   },

  {
    verb1Name: "know",
    verb1Pronunciation: "nov",
    verb2Name: "knew",
    verb2Pronunciation: "niuv",
    verb3Name: "known",
    verb3Pronunciation: "novn",
    verbTurkish: "bilmek",
    verb1Exp: "I know the answer to the question.",
    verb2Exp: "She knew him since childhood.",
    verb3Exp: "He has known about the problem.",
  },
  //   {
  //       verb1Name: 'lay',
  //       verb1Pronunciation: 'ley',
  //       verb2Name: 'laid',
  //       verb2Pronunciation: 'leyid',
  //       verb3Name: 'laid',
  //       verb3Pronunciation: 'leyid',
  //       verbTurkish: 'yaymak',
  //    verb1Exp: "",
  //     verb2Exp: "",
  //     verb3Exp: "",
  //   },
  //   {
  //       verb1Name: 'lie',
  //       verb1Pronunciation: 'lay',
  //       verb2Name: 'lay',
  //       verb2Pronunciation: 'ley',
  //       verb3Name: 'lain',
  //       verb3Pronunciation: 'layin',
  //       verbTurkish: 'yalan söylemek',
  //    verb1Exp: "",
  //     verb2Exp: "",
  //     verb3Exp: "",
  //   },

  //   {
  //       verb1Name: 'lend',
  //       verb1Pronunciation: 'lend',
  //       verb2Name: 'lent',
  //       verb2Pronunciation: 'lent',
  //       verb3Name: 'lent',
  //       verb3Pronunciation: 'lent',
  //       verbTurkish: 'ödünç vermek',
  //    verb1Exp: "",
  //     verb2Exp: "",
  //     verb3Exp: "",
  //   },
  //   {
  //       verb1Name: 'let',
  //       verb1Pronunciation: 'leet',
  //       verb2Name: 'let',
  //       verb2Pronunciation: 'leet',
  //       verb3Name: 'let',
  //       verb3Pronunciation: 'leet',
  //       verbTurkish: 'izin vermek',
  //    verb1Exp: "",
  //     verb2Exp: "",
  //     verb3Exp: "",
  //   },
  //   {
  //       verb1Name: 'lose',
  //       verb1Pronunciation: 'loos',
  //       verb2Name: 'lost',
  //       verb2Pronunciation: 'lost',
  //       verb3Name: 'lost',
  //       verb3Pronunciation: 'lost',
  //       verbTurkish: 'kaybetmek',
  //    verb1Exp: "",
  //     verb2Exp: "",
  //     verb3Exp: "",
  //   },
  //   {
  //       verb1Name: 'make',
  //       verb1Pronunciation: 'meyk',
  //       verb2Name: 'made',
  //       verb2Pronunciation: 'meyd',
  //       verb3Name: 'made',
  //       verb3Pronunciation: 'meyd',
  //       verbTurkish: 'yapmak-etmek',
  //    verb1Exp: "",
  //     verb2Exp: "",
  //     verb3Exp: "",
  //   },
  //   {
  //       verb1Name: 'meet',
  //       verb1Pronunciation: 'miit',
  //       verb2Name: 'met',
  //       verb2Pronunciation: 'met',
  //       verb3Name: 'met',
  //       verb3Pronunciation: 'met',
  //       verbTurkish: 'buluşmak',
  //    verb1Exp: "",
  //     verb2Exp: "",
  //     verb3Exp: "",
  //   },
  //   {
  //       verb1Name: 'pay',
  //       verb1Pronunciation: 'pey',
  //       verb2Name: 'paid',
  //       verb2Pronunciation: 'peid',
  //       verb3Name: 'paid',
  //       verb3Pronunciation: 'peid',
  //       verbTurkish: 'ödemek',
  //    verb1Exp: "",
  //     verb2Exp: "",
  //     verb3Exp: "",
  //   },
  //   {
  //       verb1Name: 'put',
  //       verb1Pronunciation: 'put',
  //       verb2Name: 'put',
  //       verb2Pronunciation: 'put',
  //       verb3Name: 'put',
  //       verb3Pronunciation: 'put',
  //       verbTurkish: 'koymak',
  //    verb1Exp: "",
  //     verb2Exp: "",
  //     verb3Exp: "",
  //   },
  //   {
  //       verb1Name: 'read',
  //       verb1Pronunciation: 'riid',
  //       verb2Name: 'read',
  //       verb2Pronunciation: 'red',
  //       verb3Name: 'read',
  //       verb3Pronunciation: 'red',
  //       verbTurkish: 'okumak',
  //    verb1Exp: "",
  //     verb2Exp: "",
  //     verb3Exp: "",
  //   },
  //   {
  //       verb1Name: 'ride',
  //       verb1Pronunciation: 'rayd',
  //       verb2Name: 'rode',
  //       verb2Pronunciation: 'rood',
  //       verb3Name: 'ridden',
  //       verb3Pronunciation: 'ridın',
  //       verbTurkish: 'binmek',
  //    verb1Exp: "",
  //     verb2Exp: "",
  //     verb3Exp: "",
  //   },
  //   {
  //       verb1Name: 'ring',
  //       verb1Pronunciation: 'ring',
  //       verb2Name: 'rang',
  //       verb2Pronunciation: 'reng',
  //       verb3Name: 'rung',
  //       verb3Pronunciation: 'rang',
  //       verbTurkish: 'çalmak',
  //    verb1Exp: "",
  //     verb2Exp: "",
  //     verb3Exp: "",
  //   },
  //   {
  //       verb1Name: 'rise',
  //       verb1Pronunciation: 'rays',
  //       verb2Name: 'rose',
  //       verb2Pronunciation: 'rooz',
  //       verb3Name: 'risen',
  //       verb3Pronunciation: 'raysın',
  //       verbTurkish: 'yükselmek',
  //    verb1Exp: "",
  //     verb2Exp: "",
  //     verb3Exp: "",
  //   },

  //   {
  //       verb1Name: 'say',
  //       verb1Pronunciation: 'sey',
  //       verb2Name: 'said',
  //       verb2Pronunciation: 'sed',
  //       verb3Name: 'said',
  //       verb3Pronunciation: 'sed',
  //       verbTurkish: 'söylemek',
  //    verb1Exp: "",
  //     verb2Exp: "",
  //     verb3Exp: "",
  //   },

  //   {
  //       verb1Name: 'sell',
  //       verb1Pronunciation: 'sel',
  //       verb2Name: 'sold',
  //       verb2Pronunciation: 'sold',
  //       verb3Name: 'sold',
  //       verb3Pronunciation: 'sold',
  //       verbTurkish: 'satmak',
  //    verb1Exp: "",
  //     verb2Exp: "",
  //     verb3Exp: "",
  //   },
  //   {
  //       verb1Name: 'send',
  //       verb1Pronunciation: 'send',
  //       verb2Name: 'sent',
  //       verb2Pronunciation: 'sent',
  //       verb3Name: 'sent',
  //       verb3Pronunciation: 'sent',
  //       verbTurkish: 'göndermek',
  //    verb1Exp: "",
  //     verb2Exp: "",
  //     verb3Exp: "",
  //   },
  //   {
  //       verb1Name: 'shut',
  //       verb1Pronunciation: 'şat',
  //       verb2Name: 'shut',
  //       verb2Pronunciation: 'şat',
  //       verb3Name: 'shut',
  //       verb3Pronunciation: 'şat',
  //       verbTurkish: 'kapatmak',
  //    verb1Exp: "",
  //     verb2Exp: "",
  //     verb3Exp: "",
  //   },
  //   {
  //       verb1Name: 'sing',
  //       verb1Pronunciation: 'sing',
  //       verb2Name: 'sang',
  //       verb2Pronunciation: 'seng',
  //       verb3Name: 'sung',
  //       verb3Pronunciation: 'sang',
  //       verbTurkish: 'şarkı söylemek',
  //    verb1Exp: "",
  //     verb2Exp: "",
  //     verb3Exp: "",
  //   },
  //   {
  //       verb1Name: 'sit',
  //       verb1Pronunciation: 'sit',
  //       verb2Name: 'sat',
  //       verb2Pronunciation: 'set',
  //       verb3Name: 'sat',
  //       verb3Pronunciation: 'sat',
  //       verbTurkish: 'oturmak',
  //    verb1Exp: "",
  //     verb2Exp: "",
  //     verb3Exp: "",
  //   },
  //   {
  //       verb1Name: 'sleep',
  //       verb1Pronunciation: 'sılip',
  //       verb2Name: 'slept',
  //       verb2Pronunciation: 'sılebt',
  //       verb3Name: 'slept',
  //       verb3Pronunciation: 'sılebt',
  //       verbTurkish: 'uyumak',
  //    verb1Exp: "",
  //     verb2Exp: "",
  //     verb3Exp: "",
  //   },

  //   {
  //       verb1Name: 'spend',
  //       verb1Pronunciation: 'sıpend',
  //       verb2Name: 'spent',
  //       verb2Pronunciation: 'sıpent',
  //       verb3Name: 'spent',
  //       verb3Pronunciation: 'sıpent',
  //       verbTurkish: 'harcamak',
  //    verb1Exp: "",
  //     verb2Exp: "",
  //     verb3Exp: "",
  //   },
  //   {
  //       verb1Name: 'stand',
  //       verb1Pronunciation: 'sıtend',
  //       verb2Name: 'stood',
  //       verb2Pronunciation: 'stuud',
  //       verb3Name: 'stood',
  //       verb3Pronunciation: 'stuud',
  //       verbTurkish: 'ayakta beklemek',
  //    verb1Exp: "",
  //     verb2Exp: "",
  //     verb3Exp: "",
  //   },
  //   {
  //       verb1Name: 'swim',
  //       verb1Pronunciation: 'sıvim',
  //       verb2Name: 'swam',
  //       verb2Pronunciation: 'sıvem',
  //       verb3Name: 'swum',
  //       verb3Pronunciation: 'sıvam',
  //       verbTurkish: 'yüzmek',
  //    verb1Exp: "",
  //     verb2Exp: "",
  //     verb3Exp: "",
  //   },

  {
    verb1Name: "teach",
    verb1Pronunciation: "tiiçh",
    verb2Name: "taught",
    verb2Pronunciation: "taıght",
    verb3Name: "taught",
    verb3Pronunciation: "taıght",
    verbTurkish: "öğretmek",
    verb1Exp: "I teach English at a school.",
    verb2Exp: "She taught him how to swim.",
    verb3Exp: "He has taught me a valuable lesson.",
  },

  //   {
  //       verb1Name: 'throw',
  //       verb1Pronunciation: 'tırov',
  //       verb2Name: 'threw',
  //       verb2Pronunciation: 'tıruv',
  //       verb3Name: 'thrown',
  //       verb3Pronunciation: 'tırovn',
  //       verbTurkish: 'atmak',
  //    verb1Exp: "",
  //     verb2Exp: "",
  //     verb3Exp: "",
  //   },
  //   {
  //       verb1Name: 'wake',
  //       verb1Pronunciation: 'weyk',
  //       verb2Name: 'woke',
  //       verb2Pronunciation: 'vog',
  //       verb3Name: 'woken',
  //       verb3Pronunciation: 'vokın',
  //       verbTurkish: 'uyanmak',
  //    verb1Exp: "",
  //     verb2Exp: "",
  //     verb3Exp: "",
  //   },
  //   {
  //       verb1Name: 'wear',
  //       verb1Pronunciation: 'viır',
  //       verb2Name: 'wore',
  //       verb2Pronunciation: 'vor',
  //       verb3Name: 'worn',
  //       verb3Pronunciation: 'vorn',
  //       verbTurkish: 'giyinmek',
  //    verb1Exp: "",
  //     verb2Exp: "",
  //     verb3Exp: "",
  //   },
  //   {
  //       verb1Name: 'understand',
  //       verb1Pronunciation: 'andırstend',
  //       verb2Name: 'understood',
  //       verb2Pronunciation: 'andırstud',
  //       verb3Name: 'understood',
  //       verb3Pronunciation: 'andırstud',
  //       verbTurkish: 'anlamak',
  //    verb1Exp: "",
  //     verb2Exp: "",
  //     verb3Exp: "",
  //   },
  //   {
  //       verb1Name: 'win',
  //       verb1Pronunciation: 'vin',
  //       verb2Name: 'won',
  //       verb2Pronunciation: 'von',
  //       verb3Name: 'won',
  //       verb3Pronunciation: 'von',
  //       verbTurkish: 'kazanmak',
  //    verb1Exp: "",
  //     verb2Exp: "",
  //     verb3Exp: "",
  //   },
];
