/**
 * List of irreguler verbs
 */
let verbList = [
  {
    verb1Name: "awake",
    verb1Pronunciation: "eweyk",
    verb2Name: "awoke",
    verb2Pronunciation: "evog",
    verb3Name: "awoken",
    verb3Pronunciation: "evokın",
    verbTurkish: "uyanmak",
  },
  {
    verb1Name: "be",
    verb1Pronunciation: "bi",
    verb2Name: "was/were",
    verb2Pronunciation: "vaz/vör",
    verb3Name: "been",
    verb3Pronunciation: "biin",
    verbTurkish: "olmak",
  },
  {
    verb1Name: "tell",
    verb1Pronunciation: "tel",
    verb2Name: "told",
    verb2Pronunciation: "told",
    verb3Name: "told",
    verb3Pronunciation: "told",
    verbTurkish: "söylemek anlatmak",
  },
  {
    verb1Name: "speak",
    verb1Pronunciation: "sıpik",
    verb2Name: "spoke",
    verb2Pronunciation: "sıpog",
    verb3Name: "spoken",
    verb3Pronunciation: "sıpokın",
    verbTurkish: "konuşmak",
  },
  {
    verb1Name: "see",
    verb1Pronunciation: "sii",
    verb2Name: "saw",
    verb2Pronunciation: "sov",
    verb3Name: "seen",
    verb3Pronunciation: "siın",
    verbTurkish: "görmek",
  },
  {
    verb1Name: "run",
    verb1Pronunciation: "ran",
    verb2Name: "ran",
    verb2Pronunciation: "ren",
    verb3Name: "run",
    verb3Pronunciation: "ran",
    verbTurkish: "koşmak",
  },
  {
    verb1Name: "write",
    verb1Pronunciation: "rayt",
    verb2Name: "wrote",
    verb2Pronunciation: "root",
    verb3Name: "written",
    verb3Pronunciation: "ritın",
    verbTurkish: "yazmak",
  },
  {
    verb1Name: "leave",
    verb1Pronunciation: "liıv",
    verb2Name: "left",
    verb2Pronunciation: "left",
    verb3Name: "",
    verb3Pronuncleftiation: "left",
    verbTurkish: "ayrılmak",
  },
  {
    verb1Name: "keep",
    verb1Pronunciation: "kiip",
    verb2Name: "kept",
    verb2Pronunciation: "kept",
    verb3Name: "kept",
    verb3Pronunciation: "kept",
    verbTurkish: "saklamak",
  },
  {
    verb1Name: "hold",
    verb1Pronunciation: "hoold",
    verb2Name: "held",
    verb2Pronunciation: "held",
    verb3Name: "held",
    verb3Pronunciation: "heeld",
    verbTurkish: "tutmak",
  },
  {
    verb1Name: "hear",
    verb1Pronunciation: "hiyır",
    verb2Name: "heard",
    verb2Pronunciation: "hörd",
    verb3Name: "heard",
    verb3Pronunciation: "hörd",
    verbTurkish: "duymak",
  },
  {
    verb1Name: "give",
    verb1Pronunciation: "giv",
    verb2Name: "gave",
    verb2Pronunciation: "geyv",
    verb3Name: "given",
    verb3Pronunciation: "givın",
    verbTurkish: "vermek",
  },
  {
    verb1Name: "forget",
    verb1Pronunciation: "forget",
    verb2Name: "forgot",
    verb2Pronunciation: "forgat",
    verb3Name: "forgotten",
    verb3Pronunciation: "forgatın",
    verbTurkish: "unutmak",
  },
  {
    verb1Name: "go",
    verb1Pronunciation: "go",
    verb2Name: "went",
    verb2Pronunciation: "vent",
    verb3Name: "gone",
    verb3Pronunciation: "gan",
    verbTurkish: "gitmek",
  },
  {
    verb1Name: "drive",
    verb1Pronunciation: "dırayv",
    verb2Name: "drove",
    verb2Pronunciation: "dırov",
    verb3Name: "driven",
    verb3Pronunciation: "dırayvın",
    verbTurkish: "araba sürmek",
  },
  {
    verb1Name: "feel",
    verb1Pronunciation: "fiıl",
    verb2Name: "felt",
    verb2Pronunciation: "felt",
    verb3Name: "felt",
    verb3Pronunciation: "felt",
    verbTurkish: "hissetmek",
  },
  {
    verb1Name: "think",
    verb1Pronunciation: "tink",
    verb2Name: "thought",
    verb2Pronunciation: "dout",
    verb3Name: "thought",
    verb3Pronunciation: "dout",
    verbTurkish: "düşünmek",
  },
  {
    verb1Name: "become",
    verb1Pronunciation: "bikam",
    verb2Name: "became",
    verb2Pronunciation: "bikeym",
    verb3Name: "become",
    verb3Pronunciation: "bikam",
    verbTurkish: "olmak - haline gelmek",
  },
  {
    verb1Name: "begin",
    verb1Pronunciation: "bigin",
    verb2Name: "began",
    verb2Pronunciation: "bigen",
    verb3Name: "begun",
    verb3Pronunciation: "bigan",
    verbTurkish: "başlamak",
  },
  {
    verb1Name: "buy",
    verb1Pronunciation: "bay",
    verb2Name: "bought",
    verb2Pronunciation: "bouht",
    verb3Name: "bought",
    verb3Pronunciation: "bouht",
    verbTurkish: "satın almak",
  },
  // {
  //     verb1Name: 'beat',
  //     verb1Pronunciation: 'biıt',
  //     verb2Name: 'beat',
  //     verb2Pronunciation: 'biıt',
  //     verb3Name: 'beaten',
  //     verb3Pronunciation: 'bitın',
  //     verbTurkish: 'dovmek',
  // },
  // {
  //     verb1Name: 'bend',
  //     verb1Pronunciation: 'bend',
  //     verb2Name: 'bent',
  //     verb2Pronunciation: 'bent',
  //     verb3Name: 'bent',
  //     verb3Pronunciation: 'bent',
  //     verbTurkish: 'bükmek',
  // },
  // {
  //     verb1Name: 'bet',
  //     verb1Pronunciation: 'bet',
  //     verb2Name: 'bet',
  //     verb2Pronunciation: 'bet',
  //     verb3Name: 'bet',
  //     verb3Pronunciation: 'bet',
  //     verbTurkish: 'bahse girmek',
  // },
  // {
  //     verb1Name: 'bid',
  //     verb1Pronunciation: 'biid',
  //     verb2Name: 'bid',
  //     verb2Pronunciation: 'biid',
  //     verb3Name: 'bid',
  //     verb3Pronunciation: 'biid',
  //     verbTurkish: 'emretmek',
  // },
  // {
  //     verb1Name: 'bite',
  //     verb1Pronunciation: 'bayt',
  //     verb2Name: 'bit',
  //     verb2Pronunciation: 'bit',
  //     verb3Name: 'bitten',
  //     verb3Pronunciation: 'bitın',
  //     verbTurkish: 'ısırmak',
  // },
  // {
  //     verb1Name: 'blow',
  //     verb1Pronunciation: 'bılov',
  //     verb2Name: 'blew',
  //     verb2Pronunciation: 'bıluv',
  //     verb3Name: 'blown',
  //     verb3Pronunciation: 'bılovn',
  //     verbTurkish: 'esmek',
  // },
  // {
  //     verb1Name: 'break',
  //     verb1Pronunciation: 'bireyk',
  //     verb2Name: 'broke',
  //     verb2Pronunciation: 'bırog',
  //     verb3Name: 'broken',
  //     verb3Pronunciation: 'bırokın',
  //     verbTurkish: 'kırmak',
  // },
  // {
  //     verb1Name: 'bring',
  //     verb1Pronunciation: 'bıring',
  //     verb2Name: 'brought',
  //     verb2Pronunciation: 'bıroukt',
  //     verb3Name: 'brought',
  //     verb3Pronunciation: 'bıroukt',
  //     verbTurkish: 'getirmek',
  // },
  // {
  //     verb1Name: 'build',
  //     verb1Pronunciation: 'build',
  //     verb2Name: 'built',
  //     verb2Pronunciation: 'built',
  //     verb3Name: 'built',
  //     verb3Pronunciation: 'built',
  //     verbTurkish: 'inşa etmek',
  // },
  // {
  //     verb1Name: 'burst',
  //     verb1Pronunciation: 'borst',
  //     verb2Name: 'burst',
  //     verb2Pronunciation: 'borst',
  //     verb3Name: 'burst',
  //     verb3Pronunciation: 'borst',
  //     verbTurkish: 'patlamak',
  // },

  // {
  //     verb1Name: 'catch',
  //     verb1Pronunciation: 'ketç',
  //     verb2Name: 'caught',
  //     verb2Pronunciation: 'kouht',
  //     verb3Name: 'caught',
  //     verb3Pronunciation: 'kouht',
  //     verbTurkish: 'tutmak - yakalamak',
  // },
  // {
  //     verb1Name: 'choose',
  //     verb1Pronunciation: 'çıuz',
  //     verb2Name: 'chose',
  //     verb2Pronunciation: 'çoz',
  //     verb3Name: 'chosen',
  //     verb3Pronunciation: 'çuızın',
  //     verbTurkish: 'seçmek',
  // },
  // {
  //     verb1Name: 'come',
  //     verb1Pronunciation: 'kam',
  //     verb2Name: 'came',
  //     verb2Pronunciation: 'keym',
  //     verb3Name: 'come',
  //     verb3Pronunciation: 'kam',
  //     verbTurkish: 'gelmek',
  // },
  // {
  //     verb1Name: 'cost',
  //     verb1Pronunciation: 'kost',
  //     verb2Name: 'cost',
  //     verb2Pronunciation: 'kost',
  //     verb3Name: 'cost',
  //     verb3Pronunciation: 'kost',
  //     verbTurkish: 'mâl olmak',
  // },
  // {
  //     verb1Name: 'creep',
  //     verb1Pronunciation: 'kırip',
  //     verb2Name: 'crept',
  //     verb2Pronunciation: 'kırept',
  //     verb3Name: 'crept',
  //     verb3Pronunciation: 'kırept',
  //     verbTurkish: 'emeklemek',
  // },
  // {
  //     verb1Name: 'cut',
  //     verb1Pronunciation: 'kat',
  //     verb2Name: 'cut',
  //     verb2Pronunciation: 'kat',
  //     verb3Name: 'cut',
  //     verb3Pronunciation: 'kat',
  //     verbTurkish: 'kesmek',
  // },
  // {
  //     verb1Name: 'dig',
  //     verb1Pronunciation: 'dig',
  //     verb2Name: 'dug',
  //     verb2Pronunciation: 'dag',
  //     verb3Name: 'dug',
  //     verb3Pronunciation: 'dag',
  //     verbTurkish: 'kazmak',
  // },
  // {
  //     verb1Name: 'do',
  //     verb1Pronunciation: 'du',
  //     verb2Name: 'did',
  //     verb2Pronunciation: 'did',
  //     verb3Name: 'done',
  //     verb3Pronunciation: 'dan',
  //     verbTurkish: 'yapmak',
  // },
  // {
  //     verb1Name: 'draw',
  //     verb1Pronunciation: 'dırov',
  //     verb2Name: 'drew',
  //     verb2Pronunciation: 'dıruv',
  //     verb3Name: 'drawn',
  //     verb3Pronunciation: 'dırovn',
  //     verbTurkish: 'çizmek',
  // },

  // {
  //     verb1Name: 'drink',
  //     verb1Pronunciation: 'dıring',
  //     verb2Name: 'drank',
  //     verb2Pronunciation: 'direng',
  //     verb3Name: 'drunk',
  //     verb3Pronunciation: 'dırang',
  //     verbTurkish: 'içmek',
  // },
  // {
  //     verb1Name: 'eat',
  //     verb1Pronunciation: 'iit',
  //     verb2Name: 'ate',
  //     verb2Pronunciation: 'eyt',
  //     verb3Name: 'eaten',
  //     verb3Pronunciation: 'itın',
  //     verbTurkish: 'yemek yemek',
  // },
  // {
  //     verb1Name: 'fall',
  //     verb1Pronunciation: 'fol',
  //     verb2Name: 'fell',
  //     verb2Pronunciation: 'fel',
  //     verb3Name: 'fallen',
  //     verb3Pronunciation: 'follın',
  //     verbTurkish: 'düşmek',
  // },
  // {
  //     verb1Name: 'feed',
  //     verb1Pronunciation: 'fiid',
  //     verb2Name: 'fed',
  //     verb2Pronunciation: 'fed',
  //     verb3Name: 'fed',
  //     verb3Pronunciation: 'fed',
  //     verbTurkish: 'beslemek',
  // },

  // {
  //     verb1Name: 'fight',
  //     verb1Pronunciation: 'fayt',
  //     verb2Name: 'fought',
  //     verb2Pronunciation: 'fouht',
  //     verb3Name: 'fought',
  //     verb3Pronunciation: 'fouht',
  //     verbTurkish: 'kavga etmek',
  // },
  // {
  //     verb1Name: 'find',
  //     verb1Pronunciation: 'faynd',
  //     verb2Name: 'found',
  //     verb2Pronunciation: 'faund',
  //     verb3Name: 'found',
  //     verb3Pronunciation: 'faund',
  //     verbTurkish: 'bulmak',
  // },
  // {
  //     verb1Name: 'fly',
  //     verb1Pronunciation: 'fılay',
  //     verb2Name: 'flew',
  //     verb2Pronunciation: 'fıliuv',
  //     verb3Name: 'flown',
  //     verb3Pronunciation: 'fılavn',
  //     verbTurkish: 'uçmak',
  // },
  // {
  //     verb1Name: 'forbid',
  //     verb1Pronunciation: 'forbıid',
  //     verb2Name: 'forbade',
  //     verb2Pronunciation: 'forbeyt',
  //     verb3Name: 'forbidden',
  //     verb3Pronunciation: 'forbidın',
  //     verbTurkish: 'yasaklamak',
  // },

  // {
  //     verb1Name: 'forgive',
  //     verb1Pronunciation: 'forgiv',
  //     verb2Name: 'forgave',
  //     verb2Pronunciation: 'forgeyv',
  //     verb3Name: 'forgiven',
  //     verb3Pronunciation: 'forgivın',
  //     verbTurkish: 'affetmek',
  // },
  // {
  //     verb1Name: 'freeze',
  //     verb1Pronunciation: 'fıriiz',
  //     verb2Name: 'froze',
  //     verb2Pronunciation: 'fırooz',
  //     verb3Name: 'frozen',
  //     verb3Pronunciation: 'frozın',
  //     verbTurkish: 'dondurmak',
  // },
  // {
  //     verb1Name: 'get',
  //     verb1Pronunciation: 'get',
  //     verb2Name: 'got',
  //     verb2Pronunciation: 'gat',
  //     verb3Name: 'gotten',
  //     verb3Pronunciation: 'gatın',
  //     verbTurkish: 'elde etmek',
  // },

  // {
  //     verb1Name: 'grow',
  //     verb1Pronunciation: 'gırov',
  //     verb2Name: 'grew',
  //     verb2Pronunciation: 'gırıuv',
  //     verb3Name: 'grown',
  //     verb3Pronunciation: 'gırovn',
  //     verbTurkish: 'büyümek',
  // },
  // {
  //     verb1Name: 'hang',
  //     verb1Pronunciation: 'heng',
  //     verb2Name: 'hung',
  //     verb2Pronunciation: 'hang',
  //     verb3Name: 'hung',
  //     verb3Pronunciation: 'hang',
  //     verbTurkish: 'asmak',
  // },
  // {
  //     verb1Name: 'have',
  //     verb1Pronunciation: 'hev',
  //     verb2Name: 'had',
  //     verb2Pronunciation: 'hed',
  //     verb3Name: 'had',
  //     verb3Pronunciation: 'hed',
  //     verbTurkish: 'sahip olmak',
  // },

  // {
  //     verb1Name: 'hide',
  //     verb1Pronunciation: 'hayd',
  //     verb2Name: 'hid',
  //     verb2Pronunciation: 'hid',
  //     verb3Name: 'hidden',
  //     verb3Pronunciation: 'hidın',
  //     verbTurkish: 'gizlemek',
  // },
  // {
  //     verb1Name: 'hit',
  //     verb1Pronunciation: 'hid',
  //     verb2Name: 'hit',
  //     verb2Pronunciation: 'hid',
  //     verb3Name: 'hit',
  //     verb3Pronunciation: 'hid',
  //     verbTurkish: 'vurmak',
  // },

  // {
  //     verb1Name: 'hurt',
  //     verb1Pronunciation: 'hört',
  //     verb2Name: 'hurt',
  //     verb2Pronunciation: 'hört',
  //     verb3Name: 'hurt',
  //     verb3Pronunciation: 'hört',
  //     verbTurkish: 'incinmek',
  // },

  // {
  //     verb1Name: 'know',
  //     verb1Pronunciation: 'nov',
  //     verb2Name: 'knew',
  //     verb2Pronunciation: 'niuv',
  //     verb3Name: 'known',
  //     verb3Pronunciation: 'novn',
  //     verbTurkish: 'bilmek',
  // },
  // {
  //     verb1Name: 'lay',
  //     verb1Pronunciation: 'ley',
  //     verb2Name: 'laid',
  //     verb2Pronunciation: 'leyid',
  //     verb3Name: 'laid',
  //     verb3Pronunciation: 'leyid',
  //     verbTurkish: 'yaymak',
  // },
  // {
  //     verb1Name: 'lie',
  //     verb1Pronunciation: 'lay',
  //     verb2Name: 'lay',
  //     verb2Pronunciation: 'ley',
  //     verb3Name: 'lain',
  //     verb3Pronunciation: 'layin',
  //     verbTurkish: 'yalan söylemek',
  // },

  // {
  //     verb1Name: 'lend',
  //     verb1Pronunciation: 'lend',
  //     verb2Name: 'lent',
  //     verb2Pronunciation: 'lent',
  //     verb3Name: 'lent',
  //     verb3Pronunciation: 'lent',
  //     verbTurkish: 'ödünç vermek',
  // },
  // {
  //     verb1Name: 'let',
  //     verb1Pronunciation: 'leet',
  //     verb2Name: 'let',
  //     verb2Pronunciation: 'leet',
  //     verb3Name: 'let',
  //     verb3Pronunciation: 'leet',
  //     verbTurkish: 'izin vermek',
  // },
  // {
  //     verb1Name: 'lose',
  //     verb1Pronunciation: 'loos',
  //     verb2Name: 'lost',
  //     verb2Pronunciation: 'lost',
  //     verb3Name: 'lost',
  //     verb3Pronunciation: 'lost',
  //     verbTurkish: 'kaybetmek',
  // },
  // {
  //     verb1Name: 'make',
  //     verb1Pronunciation: 'meyk',
  //     verb2Name: 'made',
  //     verb2Pronunciation: 'meyd',
  //     verb3Name: 'made',
  //     verb3Pronunciation: 'meyd',
  //     verbTurkish: 'yapmak-etmek',
  // },
  // {
  //     verb1Name: 'meet',
  //     verb1Pronunciation: 'miit',
  //     verb2Name: 'met',
  //     verb2Pronunciation: 'met',
  //     verb3Name: 'met',
  //     verb3Pronunciation: 'met',
  //     verbTurkish: 'buluşmak',
  // },
  // {
  //     verb1Name: 'pay',
  //     verb1Pronunciation: 'pey',
  //     verb2Name: 'paid',
  //     verb2Pronunciation: 'peid',
  //     verb3Name: 'paid',
  //     verb3Pronunciation: 'peid',
  //     verbTurkish: 'ödemek',
  // },
  // {
  //     verb1Name: 'put',
  //     verb1Pronunciation: 'put',
  //     verb2Name: 'put',
  //     verb2Pronunciation: 'put',
  //     verb3Name: 'put',
  //     verb3Pronunciation: 'put',
  //     verbTurkish: 'koymak',
  // },
  // {
  //     verb1Name: 'read',
  //     verb1Pronunciation: 'riid',
  //     verb2Name: 'read',
  //     verb2Pronunciation: 'red',
  //     verb3Name: 'read',
  //     verb3Pronunciation: 'red',
  //     verbTurkish: 'okumak',
  // },
  // {
  //     verb1Name: 'ride',
  //     verb1Pronunciation: 'rayd',
  //     verb2Name: 'rode',
  //     verb2Pronunciation: 'rood',
  //     verb3Name: 'ridden',
  //     verb3Pronunciation: 'ridın',
  //     verbTurkish: 'binmek',
  // },
  // {
  //     verb1Name: 'ring',
  //     verb1Pronunciation: 'ring',
  //     verb2Name: 'rang',
  //     verb2Pronunciation: 'reng',
  //     verb3Name: 'rung',
  //     verb3Pronunciation: 'rang',
  //     verbTurkish: 'çalmak',
  // },
  // {
  //     verb1Name: 'rise',
  //     verb1Pronunciation: 'rays',
  //     verb2Name: 'rose',
  //     verb2Pronunciation: 'rooz',
  //     verb3Name: 'risen',
  //     verb3Pronunciation: 'raysın',
  //     verbTurkish: 'yükselmek',
  // },

  // {
  //     verb1Name: 'say',
  //     verb1Pronunciation: 'sey',
  //     verb2Name: 'said',
  //     verb2Pronunciation: 'sed',
  //     verb3Name: 'said',
  //     verb3Pronunciation: 'sed',
  //     verbTurkish: 'söylemek',
  // },

  // {
  //     verb1Name: 'sell',
  //     verb1Pronunciation: 'sel',
  //     verb2Name: 'sold',
  //     verb2Pronunciation: 'sold',
  //     verb3Name: 'sold',
  //     verb3Pronunciation: 'sold',
  //     verbTurkish: 'satmak',
  // },
  // {
  //     verb1Name: 'send',
  //     verb1Pronunciation: 'send',
  //     verb2Name: 'sent',
  //     verb2Pronunciation: 'sent',
  //     verb3Name: 'sent',
  //     verb3Pronunciation: 'sent',
  //     verbTurkish: 'göndermek',
  // },
  // {
  //     verb1Name: 'shut',
  //     verb1Pronunciation: 'şat',
  //     verb2Name: 'shut',
  //     verb2Pronunciation: 'şat',
  //     verb3Name: 'shut',
  //     verb3Pronunciation: 'şat',
  //     verbTurkish: 'kapatmak',
  // },
  // {
  //     verb1Name: 'sing',
  //     verb1Pronunciation: 'sing',
  //     verb2Name: 'sang',
  //     verb2Pronunciation: 'seng',
  //     verb3Name: 'sung',
  //     verb3Pronunciation: 'sang',
  //     verbTurkish: 'şarkı söylemek',
  // },
  // {
  //     verb1Name: 'sit',
  //     verb1Pronunciation: 'sit',
  //     verb2Name: 'sat',
  //     verb2Pronunciation: 'set',
  //     verb3Name: 'sat',
  //     verb3Pronunciation: 'sat',
  //     verbTurkish: 'oturmak',
  // },
  // {
  //     verb1Name: 'sleep',
  //     verb1Pronunciation: 'sılip',
  //     verb2Name: 'slept',
  //     verb2Pronunciation: 'sılebt',
  //     verb3Name: 'slept',
  //     verb3Pronunciation: 'sılebt',
  //     verbTurkish: 'uyumak',
  // },

  // {
  //     verb1Name: 'spend',
  //     verb1Pronunciation: 'sıpend',
  //     verb2Name: 'spent',
  //     verb2Pronunciation: 'sıpent',
  //     verb3Name: 'spent',
  //     verb3Pronunciation: 'sıpent',
  //     verbTurkish: 'harcamak',
  // },
  // {
  //     verb1Name: 'stand',
  //     verb1Pronunciation: 'sıtend',
  //     verb2Name: 'stood',
  //     verb2Pronunciation: 'stuud',
  //     verb3Name: 'stood',
  //     verb3Pronunciation: 'stuud',
  //     verbTurkish: 'ayakta beklemek',
  // },
  // {
  //     verb1Name: 'swim',
  //     verb1Pronunciation: 'sıvim',
  //     verb2Name: 'swam',
  //     verb2Pronunciation: 'sıvem',
  //     verb3Name: 'swum',
  //     verb3Pronunciation: 'sıvam',
  //     verbTurkish: 'yüzmek',
  // },
  // {
  //     verb1Name: 'take',
  //     verb1Pronunciation: 'teyk',
  //     verb2Name: 'took',
  //     verb2Pronunciation: 'tuuk',
  //     verb3Name: 'taken',
  //     verb3Pronunciation: 'teykın',
  //     verbTurkish: 'almak',
  // },
  // {
  //     verb1Name: 'teach',
  //     verb1Pronunciation: 'tiiçh',
  //     verb2Name: 'taught',
  //     verb2Pronunciation: 'taıght',
  //     verb3Name: 'taught',
  //     verb3Pronunciation: 'taıght',
  //     verbTurkish: 'öğretmek',
  // },

  // {
  //     verb1Name: 'throw',
  //     verb1Pronunciation: 'tırov',
  //     verb2Name: 'threw',
  //     verb2Pronunciation: 'tıruv',
  //     verb3Name: 'thrown',
  //     verb3Pronunciation: 'tırovn',
  //     verbTurkish: 'atmak',
  // },
  // {
  //     verb1Name: 'wake',
  //     verb1Pronunciation: 'weyk',
  //     verb2Name: 'woke',
  //     verb2Pronunciation: 'vog',
  //     verb3Name: 'woken',
  //     verb3Pronunciation: 'vokın',
  //     verbTurkish: 'uyanmak',
  // },
  // {
  //     verb1Name: 'wear',
  //     verb1Pronunciation: 'viır',
  //     verb2Name: 'wore',
  //     verb2Pronunciation: 'vor',
  //     verb3Name: 'worn',
  //     verb3Pronunciation: 'vorn',
  //     verbTurkish: 'giyinmek',
  // },
  // {
  //     verb1Name: 'understand',
  //     verb1Pronunciation: 'andırstend',
  //     verb2Name: 'understood',
  //     verb2Pronunciation: 'andırstud',
  //     verb3Name: 'understood',
  //     verb3Pronunciation: 'andırstud',
  //     verbTurkish: 'anlamak',
  // },
  // {
  //     verb1Name: 'win',
  //     verb1Pronunciation: 'vin',
  //     verb2Name: 'won',
  //     verb2Pronunciation: 'von',
  //     verb3Name: 'won',
  //     verb3Pronunciation: 'von',
  //     verbTurkish: 'kazanmak',
  // },
];
